version: 2

builds:
  - binary: gh-slackdump
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  generate_release_notes: true
