version: 2

builds:
  - binary: gh-slackdump
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  use: github
